baseURL = "https://persdre.github.io/intermine-training-portal"

languageCode = "en-uk"
DefaultContentLanguage = "en"
title = "InterMine Training Portal"
theme = "training-portal-theme"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"
publishDir = "docs"

[params]
ordersectionsby = "weight"  # ordersectionsby = "title"
disableSearch = false       # default is false
disableReadmoreNav = false  # set true to hide prev/next navigation, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = true  # set true to open shortcuts links to a new tab/window

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "InterMine"
url = "http://intermine.org/"
weight = 1

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i>"
url = "https://github.com/intermine"
weight = 2


